name: Bergen Meadow - Build and Deploy

on:
  push:
    branches:
      - 'deploy/production'
    paths:
      - 'apps/bergen-meadow/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./apps/bergen-meadow/Dockerfile
          tags: rjhilgefort/bergen-meadow:latest

      - name: Build Monorepo Packages
        run: |
          npm install
          npm run build

      - name: Deploy to Portainer
        uses: ./packages/portainer-stack-redeploy-action
        with:
          host: '${{ secrets.PORTAINER_URL }}'
          accessToken: '${{ secrets.PORTAINER_ACCESS_TOKEN }}'
          stackName: 'bergen-meadow-site'
