name: Ally Personal - Build and Deploy

on:
  push:
    branches:
      - 'deploy/production'
    paths:
      - 'apps/ally-personal/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./apps/ally-personal/Dockerfile
          tags: rjhilgefort/ally-personal:latest

      # https://github.com/wirgen/portainer-stack-redeploy-action/tree/v1.1
      # https://app.swaggerhub.com/apis/portainer/portainer-ce/2.27.1#/stacks/StackUpdate
      # - name: Deploy to Portainer
      #   uses: wirgen/portainer-stack-redeploy-action@v1.1
      #   with:
      #     portainerUrl: '${{ secrets.PORTAINER_URL }}'
      #     accessToken: '${{ secrets.PORTAINER_ACCESS_TOKEN }}'
      #     stackId: 49
      #     # endpointId: 3
